version: "2"
services:
  feedernet:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: feedernet
    links:
      - mongo
    ports:
      - "4000:4000"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: on-failure
  mongo:
    container_name: mongo
    image: andresvidal/rpi3-mongodb3
    command: ["mongod", "--journal"]
    ports:
      - "27017:27017"
    restart: on-failure
    volumes:
      - "./data:/data/db"
